# Analytics Engineering Assessment — dbt project
# Use with dbt-duckdb (pip install dbt-duckdb)

name: 'ae_assessment'
version: '1.0.0'
config-version: 2

profile: 'ae_assessment'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  ae_assessment:
    +schema: raw

vars:
  order_updated_at_cutoff_date: '1900-01-01'

models:
  ae_assessment:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts
      +materialized: incremental
      +incremental_strategy: delete+insert

tests:
  ae_assessment:
    +severity: error
